### ISSUE TITLE
MOSI.pkl

### ISSUE THREAD

**Issue by fly-pandas** [WasifurRahman/BERT_multimodal_transformer#12]
I get mosi.pkl from https://www.dropbox.com/s/sv94igp7zi3rsj1/mosi.pkl?dl=1. 
When I open mosi.pkl, I find it just has four labels (facet, covarep, glove, label) not five labels (words, visual, acoustic, label_id, segment). Can you give me mosi.pkl includes five labels (words, visual, acoustic, label_id, segment)? Thanks!

**Comment by HDU-g** [comment]
MOSI.pkl in dropbox is wrong. It just has four labels (facet, covarep, glove, output_label). And MOSI.pkl in Google Drive is right. In your code, you need to five labels(words, visual, acoustic, label_id, segment).

**Comment by fly-pandas** [comment]
MOSI.pkl in Google Drive is right. It has five labels(words, visual, acoustic label, segment) in train,valid and test.

**Comment by RE-N-Y** [comment]
@matalvepu Could you take a look at the Dropbox link? I believe you uploaded the one in Dropbox right?

**Comment by fly-pandas** [comment]
Thank you very much for your reply. The dataset in GoogleDrive is what your code uses.

**Comment by RE-N-Y** [comment]
We will be resolving the issue shortly by removing dropbox link
