### ISSUE TITLE
Run download_datasets.sh file erro

### ISSUE THREAD

**Issue by yangxiao1211** [WasifurRahman/BERT_multimodal_transformer#24]
An error has occurred using proxy: None
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=12HbavGOtoVCqicvSYWl3zImli5Jz0Nou (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
An error has occurred using proxy: None
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1VJhSc2TGrPU8zJSVTYwn5kfuG47VaNQ3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

**Comment by RE-N-Y** [comment]
You can download the model weights directly from dropbox by running:

```
wget https://www.dropbox.com/s/sv94igp7zi3rsj1/mosi.pkl?dl=1
wget https://www.dropbox.com/s/995dvj3506gvk5a/mosei.pkl?dl=1
```
