### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by PierreColombo** [WasifurRahman/BERT_multimodal_transformer#7]
Hi,
Thanks a lot for your work :)
There is a little typo in the readme 
mutlimodal_driver.py
instead of multimodal_driver.py
Cheers

**Comment by PierreColombo** [comment]
Hi, 
np.zeros((pad_length, ACOUSTIC_DIM))  ligne 222 and 225 need to be updated from np.zeros(pad_length, ACOUSTIC_DIM) to np.zeros((pad_length, ACOUSTIC_DIM)) :) in multimodal driver

**Comment by RE-N-Y** [comment]
@PierreColombo  Thanks for pointing it out! I will take a look and resolve these sometime this week
